sonar.host.url=http://localhost:9000
sonar.token=squ_0578451a7a62e930ee1e721b41a69ecc9b812f3f
sonar.projectKey=todo-list
sonar.projectName=todo-list
sonar.sources=.
sonar.javascript.node.maxspace=2048